<!-- Tweet button -->
<a href="https://twitter.com/share" class="twitter-share-button" data-url="http://couchbase.com/mobile" data-text="The NoSQL database solution for mobile — everything you need to build always-available apps that work online & offline." data-hashtags="couchbase, couchbasemobile">Tweet</a>
<!-- Twitter follow button -->
<a href="https://twitter.com/CouchbaseMobile" class="twitter-follow-button" data-show-count="false">Follow @CouchbaseMobile</a>
<script>
window.twttr=(function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],t=window.twttr||{};if(d.getElementById(id))return;js=d.createElement(s);js.id=id;js.src="https://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);t._e=[];t.ready=function(f){t._e.push(f);};return t;}(document,"script","twitter-wjs"));
</script>